package org.vaadin.platform.ui.navigation;

/**
 * NavigationEvent contains information about navigation target view as well as
 * the parameters passed for the view.
 */
public class NavigationEvent {

    /**
     * EventType tells how NavigationEvent was generated.
     */
    public enum EventType {
        /**
         * Event was generated by calling navigation manager programmatically.
         */
        PROGRAMMATIC,

        /**
         * Event was generated by user changing the URI fragment or for example
         * pressing browser back or forward button.
         */
        FRAGMENT;
    }

    private final String view;
    private final String parameters;
    private final EventType type;

    public NavigationEvent(String view, String parameters, EventType type) {
        this.view = view;
        this.parameters = parameters;
        this.type = type;
    }

    /**
     * @return name of the target view
     */
    public String getView() {
        return view;
    }

    /**
     * @return parameters being passed for the target view
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * @return type of the event determined by how the event originated.
     */
    public EventType getType() {
        return type;
    }

    @Override
    public String toString() {
        return getClass().getCanonicalName() + ", type: " + type + ", view: " + view + ", params: " + parameters;
    }
}
